In [2]:
import torch
from sympy.printing.pytorch import torch


In [33]:
# 数组的创建
x = torch.arange(12) #生成0-12的数组
y = x.shape # torch.Size([12])
z = x.numel() # 标量
h = x.reshape(3,4)
i = torch.zeros((2,3,4) )
j = torch.ones((1,2,3))


In [35]:
# 创建数组
X = torch.tensor([[1,2,3], [4,5,6]])
Y  =X.shape
print(Y)

torch.Size([2, 3])


In [ ]:
# 算数求值 ，直接按位计算
# 哈马丹积

In [42]:
# 数组的拼接
x = torch.arange(16,dtype=torch.float32).reshape((4,4))
y =  torch.tensor([[2,1,4,3],[3,2,4,5],[6,5,4,5],[3,3,2,1]])
# 按维度拼接
# 可以使用 keepdimension = true 保持维度
z =torch.cat((x,y), dim = 0) # 注意书写规范
print(z)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [ 2.,  1.,  4.,  3.],
        [ 3.,  2.,  4.,  5.],
        [ 6.,  5.,  4.,  5.],
        [ 3.,  3.,  2.,  1.]])


In [ ]:
# 张量的赋值运算
x == y

In [ ]:
# 求和
x.sum()

In [3]:
## 广播机制
# 广播机制适用于对维度不同的数组操作执行
a = torch.arange(3).reshape((3,1))
b = torch.ones(2).reshape((1,2))
print(a)
print(b)
print(a+b)


tensor([[0],
        [1],
        [2]])
tensor([[1., 1.]])
tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])


In [ ]:
# 广播机制的使用条件
# 对标量广播 ： a(张量） + b
# 从右到左逐个比较维度。
# 维度要么相等，要么有一个为 1 才能进行广播。


In [54]:
#元素的访问 和特定元素的写入
x = torch.arange(12).reshape((3,4)) #从 0 开始
print(x[-1]) # 访问最后一个元素
x[1,2] = 9
print(x)

tensor([ 8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])


In [62]:
# 元素地址的检索
X = torch.zeros(12).reshape((3,4))
Y = torch.arange(12).reshape((3,4))
before = id(Y)
Y = Y + X  # 创建新对象时地址发生改变
id(Y) == before
Z = Y
before_Z =id(Z)
Z.add_(X) # 带有下划线时进行园地操作
z[:] = x + y # 切片赋值也是原地赋值的一种
print(id(Z) == before_Z) # 原地操作时数据不发生改变


# 了解了两种赋值方法： 下划线函数法和 切片赋值法都是原地赋值的一种

True


In [ ]:
#pytorch 和  numpy 的转换
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)
a = torch.

In [63]:
#数据预处理

# 文件的操作

# 创建文件
# 创建文件一般使用os库 ， 关键操作在于makedirs，提供拼接的参数，
# 修改文件 使用 with open (data_file,
import os
os.makedirs(os.path.join('...','data'),exist_ok=True) # exist_ok防止重复报错
data_file = os.path.join(os.path.join('...','data'),'data.csv')
with open(data_file,'w') as f: # w代表write , f是简写
    f.write('a,b,c\n')
    f.write('a,b,c\n')
    f.write('a,b,NA\n')

# 读取文件 ，一般使用  pandas库存
import pandas as pd
data =pd.read_csv(data_file)
print(data)
data # 自动使用html实现

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '...\\data'

In [ ]:
# 对数字插值/删除
inputs, outputs = data.iloc[:, 0 :2],data.iloc[:,3] # index loaction ,访问指定数据的地址
inputs = inputs.fillna(inputs.mean())
# 填充 数字型下的NA位置并使用 均值替代
print(inputs)

In [ ]:
# 对类别值的操作
inputs = pd.get_dummies(inputs,dummy_na = True,dtype= int) # 把缺失值当成 独立类别处理
print(inputs)


In [64]:
# 把CSV 转化成 tensor
import torch
x,y = torch.tensor(inputs.values),torch.tensor(outputs.values)

NameError: name 'inputs' is not defined

In [7]:
class Animal:
	def __init__(self,name):
	    self.name = name
class Dog(Animal):
	def __init__(self,name,breed): #传参先传入本身， 使用 self 字样
		super().__init__(name)
		self.breed =breed