In [1]:
import torch
# 矩阵的转置
A = torch.randn(2,3)
A.T
print(A.T)


tensor([[ 1.2987,  0.4002],
        [-0.5315,  0.8035],
        [ 0.4558,  0.0021]])


In [2]:
 B = A.clone()

In [4]:
print(id(B) == id(A))
B = A
print(id(B) == id(A)) # .clone()创建地址不同的拷贝

False
True


In [27]:
# 按维求和
A = torch.randn(2,3,5)
B =A.sum(axis = 0)
print(B)
B = A.sum(axis =1)
print(B)
C =A.sum(axis =2 )
print(C)

# 按维求平均
x = torch.randn(2,3)
y =x.mean(axis=1)
print("the mean of x along the axis =1 is ",y)
# 按维拼接

tensor([[-3.2157, -2.7366, -0.9538,  0.7594, -0.9968],
        [-0.2961, -1.3020,  0.1624,  0.8483,  0.5144],
        [ 3.1789, -0.8352, -0.6248,  1.5247,  2.1939]])
tensor([[ 2.9628, -1.7690, -0.0590,  2.7223,  0.8723],
        [-3.2956, -3.1047, -1.3572,  0.4101,  0.8392]])
tensor([[-2.4843,  3.5506,  3.6630],
        [-4.6591, -3.6236,  1.7744]])
the mean of x along the axis =1 is  tensor([0.5535, 1.0863])


In [50]:
# dot product
x = torch.randn(3)
y = torch.randn(3)
# dot.传入一维数组

print(torch.dot(x,y))
A = torch.randn(2,3)
B = torch.randn(3,6)
print(torch.matmul(A,B)) # matrix multplication
print(torch.mm(A,B))
print(A @ B ) # 语法糖

tensor(-0.0955)
tensor([[ 0.5580, -0.6712, -2.3209, -3.7703,  1.5595,  0.2721],
        [ 0.2837,  1.1547, -2.1915,  0.4237, -2.3753,  2.0286]])
tensor([[ 0.5580, -0.6712, -2.3209, -3.7703,  1.5595,  0.2721],
        [ 0.2837,  1.1547, -2.1915,  0.4237, -2.3753,  2.0286]])
tensor([[ 0.5580, -0.6712, -2.3209, -3.7703,  1.5595,  0.2721],
        [ 0.2837,  1.1547, -2.1915,  0.4237, -2.3753,  2.0286]])


In [51]:
torch.norm(x)

tensor(1.9170)

In [2]:
# l1 范数： 直接每个元素进行绝对值的求和
L1_norm = torch.norm(x,p=1 )
# l2 范数： 每个元素的平方和求根
L2_norm = torch.norm(x,p=2)
print(L1_norm)
print(L2_norm)

NameError: name 'torch' is not defined

In [3]:
#求导
#标量对向量的求导

#向量对标量的求导

# 向量对向量的求导

In [2]:
# 矩阵的自动求导
import torch
x = torch.arange(4.0)
x.requires_grad_(True) #显示梯度的存储
x.grad # 求解梯度
y = 2 * torch.dot(x,x)
y.backward()
x.grad
x.grad == 4 * x


tensor([True, True, True, True])

In [3]:
x.grad.zero_()# 梯度清零
u = y.detach() # 把y当成x的常数
z= u * x
z.sum().backward()
x.grad == u



tensor([True, True, True, True])

SyntaxError: incomplete input (1111836870.py, line 6)

In [ ]:
    a